#!/usr/bin/env python3
"""Generate the bookless skill-book items and their localized names.

These are the skills that have NO SkillBook in vanilla (SPEC §5). Items mirror the
vanilla book fields (SkillTrained / LvlSkillTrained 1,3,5,7,9 / NumLevelsTrained 2).
Re-run to regenerate; output paths are relative to the mod's media folder.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
MEDIA = os.path.normpath(os.path.join(HERE, "..", "42", "media"))

# skill key (== SkillTrained string == SkillBook[] key) -> (EN name, PT name)
SKILLS = {
    # Passive
    "Strength":   ("Strength",   "Força"),
    "Fitness":    ("Fitness",    "Condicionamento"),
    "Sprinting":  ("Sprinting",  "Corrida"),
    "Lightfoot":  ("Lightfooted","Pés Leves"),
    "Nimble":     ("Nimble",     "Agilidade"),
    "Sneak":      ("Sneaking",   "Furtividade"),
    # Combat
    "Axe":        ("Axe",        "Machado"),
    "Blunt":      ("Long Blunt", "Contundente Longo"),
    "SmallBlunt": ("Short Blunt","Contundente Curto"),
    "SmallBlade": ("Short Blade","Lâmina Curta"),
    "Spear":      ("Spear",      "Lança"),
}

ROMAN = ["I", "II", "III", "IV", "V"]
LVL = [1, 3, 5, 7, 9]                 # vanilla LvlSkillTrained per tier
PAGES = [220, 260, 300, 340, 380]     # NumberOfPages per tier


def item_block(skill, tier):
    return f"""    item Book{skill}{tier+1}
    {{
        DisplayCategory = SkillBook,
        ItemType = base:literature,
        Weight = 1.0,
        Icon = Book8,
        SkillTrained = {skill},
        LvlSkillTrained = {LVL[tier]},
        NumLevelsTrained = 2,
        NumberOfPages = {PAGES[tier]},
        StaticModel = BookBrown,
        WorldStaticModel = BookBrown_Ground,
    }}"""


def gen_items():
    blocks = []
    for skill in SKILLS:
        for tier in range(5):
            blocks.append(item_block(skill, tier))
    body = "\n\n".join(blocks)
    header = ("/* GENERATED by tools/gen_bookless.py - do not edit by hand.\n"
              "   Skill books for skills with no vanilla book (SPEC §5). */\n")
    return f"{header}module SBW\n{{\n{body}\n}}\n"


def gen_itemnames(lang):
    idx = 0 if lang == "EN" else 1
    lines = [f'    "SBW.EmptySkillBook": '
             + ('"Empty Skill Book"' if lang == "EN" else '"Livro de Habilidade em Branco"')]
    for skill, names in SKILLS.items():
        disp = names[idx]
        for tier in range(5):
            lines.append(f'    "SBW.Book{skill}{tier+1}": "{disp} {ROMAN[tier]}"')
    return "{\n" + ",\n".join(lines) + "\n}\n"


def write(path, text):
    full = os.path.join(MEDIA, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    print("wrote", path)


if __name__ == "__main__":
    write("scripts/items_skillbooks_bookless.txt", gen_items())
    write("lua/shared/Translate/EN/ItemName.json", gen_itemnames("EN"))
    write("lua/shared/Translate/PTBR/ItemName.json", gen_itemnames("PT"))
